from ..base import supplier
from ..base.adapter import Adapter
from ..base.downloaders import FTPDownloader
from ..base.parsers import CSVParser


class Drako(supplier.Supplier):
    files = [
        {
            'name': 'Main',
            'mapping': {
                'multiplayer_it.txt': (
                    'Nome_Cat',
                    'ID_Articolo',
                    'Codice_Vendor',
                    'Nome',
                    'Descrizione',
                    'Peso',
                    'Prezzo_listino',
                    'Prezzo_promo',
                    'Prezzo',
                    'Produttore',
                    'IVA',
                    'Dispo',
                    'Dispo_Fut',
                    'Data_Dispo',
                    'EAN',
                    'Indirizzo Immagine',
                    'Testo Prodotto',
                ),
            },
        },
    ]

    downloader = FTPDownloader(
        hostname='ftp.drako.it',
        username='Multiplayer_it',
        password='ErNE4IWX')

    parser = CSVParser(
        delimiter='\t',
        linebreak='\n',
        skip_first=True)

    mapping = Adapter(
        barcode='EAN',
        supplier_code='Codice_Vendor',
        supplier_price=lambda self, item: float(item['Prezzo_listino'].replace(',', '.')) if item['Prezzo_listino'] else None,
        supplier_quantity='Dispo',
        name='Nome',
        description=lambda self, item: '<br><br>'.join([item['Descrizione'], item['Testo Prodotto']]) if item['Descrizione'] and item['Testo Prodotto'] else item['Testo Prodotto'],
        image='Indirizzo Immagine',
        date=lambda self, item: item['Data_Dispo'] or None)

    def validate(self, item):
        assert item['Nome_Cat'] in CATEGORIES
        assert item['Nome_Cat'] not in EXCLUDED_CATEGORIES
        assert item['Produttore'] not in EXCLUDED_MANUFACTURERS


CATEGORIES = (
    'Accessori LAN|Accessori Montaggio',
    'Accessori LAN|Cavo di rete',
    'Accessori LAN|Powerline',
    'Accessori|Adattatori USB/FireWire/BT',
    'Accessori|Batterie / Caricatori',
    'Accessori|Connessioni Esterne',
    'Accessori|Controller',
    'Accessori|Floppy',
    'Accessori|Hub USB / Firewire',
    'Accessori|Lettori MemoryCard',
    'Accessori|Lettori Mp3/Mp4/JPG',
    'Accessori|Multiprese',
    'Accessori|Pannelli Frontali',
    'Accessori|Pulizia PC & Monitor',
    'Accessori|Saldatori / Accessori',
    'Accessori|Software & SO',
    'Accessori|Speciale NATALE',
    'Accessori|Supporti TV / LCD',
    'Accessori|Viti Case & Fan',
    'Accessori|Webcam',
    'Alimentatori|Accessori',
    'Alimentatori|Antec',
    'Alimentatori|Arctic Cooling',
    'Alimentatori|Cooler Master',
    'Alimentatori|Corsair',
    'Alimentatori|Enermax',
    'Alimentatori|NZXT',
    'Alimentatori|Nexus',
    'Alimentatori|OCZ',
    'Alimentatori|Seasonic',
    'Alimentatori|Silverstone',
    'Alimentatori|Tagan',
    'Alimentatori|Zalman',
    'Alimentatori|fino a 1100w',
    'Alimentatori|fino a 500w',
    'Alimentatori|fino a 800w',
    'Alimentatori|oltre 1100w',
    'Arctic RC Toys|Accessori',
    'Arctic RC Toys|Aqua Rider',
    'Arctic RC Toys|Land Rider',
    'Arctic RC Toys|Sky Rider',
    'Audio|Amplificatori',
    'Audio|Cuffie/Headset/Auricolari',
    'Audio|Schede Audio',
    'BitFenix|BitFenix - Accessori',
    'BitFenix|BitFenix - Colossus',
    'BitFenix|BitFenix - Merc',
    'BitFenix|BitFenix - Outlaw',
    'BitFenix|BitFenix - Shinobi',
    'BitFenix|BitFenix - Survivor',
    'Box Esterni HD|Accessori',
    'Box Esterni HD|Box SATA / eSATA',
    'Box Esterni HD|Box USB',
    'CD / DVD / BluRay|CD, DVD e Accessori',
    'CD / DVD / BluRay|Drive DVD / Blu-Ray',
    'CPU Cooler|Socket 115X (Intel)',
    'CPU Cooler|Socket 1366 (Intel)',
    'CPU Cooler|Socket 2011 (Intel)',
    'CPU Cooler|Socket 754/9XX (AMD)',
    'CPU Cooler|Socket 775 (Intel)',
    'CPU Cooler|Socket AM2/AM2+/AM3 (AMD)',
    'Case HTPC|HTPC - Akasa',
    'Case HTPC|HTPC - Lian Li',
    'Case HTPC|HTPC - Silverstone',
    'Case|Aerocool',
    'Case|Akasa',
    'Case|Antec',
    'Case|Aplus',
    'Case|CM Storm',
    '"Case|Case Rack 19""',
    'Case|Chieftec',
    'Case|Cooler Master',
    'Case|Corsair',
    'Case|Cubitek',
    'Case|DimasTech',
    'Case|Enermax',
    'Case|Fractal',
    'Case|Gigabyte',
    'Case|IN WIN',
    'Case|Kit Fonoassorbenti',
    'Case|NZXT',
    'Case|Nexus',
    'Case|OrigenAE',
    'Case|Raidmax',
    'Case|Sharkoon',
    'Case|Thermaltake',
    'Case|Zalman',
    'Cavi / Adattatori|Cavi / Adattatori FAN',
    'Cavi / Adattatori|Cavi / Adattatori PSU',
    'Cavi Audio/Video|cavi / adattatori DVI',
    'Cavi Audio/Video|cavi / adattatori HDMI',
    'Cavi Audio/Video|cavi / adattatori JACK',
    'Cavi Audio/Video|cavi / adattatori RCA',
    'Cavi Audio/Video|cavi / adattatori S-VGA',
    'Cavi Audio/Video|cavi / adattatori SCART',
    'Cavi Audio/Video|cavi / adattatori TOSLINK',
    'Cavi Dati|cavi / adattatori  SATA / eSATA',
    'Cavi Dati|cavi / adattatori FIREWIRE',
    'Cavi Dati|cavi / adattatori IDE / ATA',
    'Cavi Dati|cavi / adattatori SAS',
    'Cavi Dati|cavi / adattatori USB',
    'Chipset Cooler|EK Water Blocks',
    'Chipset Cooler|Watercool',
    'Connettori, Plug & Raccordi|Adattatori',
    'Connettori, Plug & Raccordi|Adattatori Pompa',
    'Connettori, Plug & Raccordi|Connettori 10/6mm',
    'Connettori, Plug & Raccordi|Connettori 10/8mm',
    'Connettori, Plug & Raccordi|Connettori 11/8mm',
    'Connettori, Plug & Raccordi|Connettori 13/10mm',
    'Connettori, Plug & Raccordi|Connettori 16/10mm',
    'Connettori, Plug & Raccordi|Connettori 16/11mm',
    'Connettori, Plug & Raccordi|Connettori 16/13mm',
    'Connettori, Plug & Raccordi|Connettori 19/13mm',
    'Connettori, Plug & Raccordi|Connettori 6/4mm',
    'Connettori, Plug & Raccordi|Connettori 8/6mm',
    'Connettori, Plug & Raccordi|Guarnizioni O-Ring',
    'Connettori, Plug & Raccordi|Kit Connettori',
    'Connettori, Plug & Raccordi|Plug Innesto Rapido',
    'Connettori, Plug & Raccordi|Portatubo / Raccordi',
    'Connettori, Plug & Raccordi|Raccordi',
    'Connettori, Plug & Raccordi|Rubinetti & Tappi',
    'Dissipatori CPU|AMD Socket 754/9XX',
    'Dissipatori CPU|AMD Socket AM2/AM3',
    'Dissipatori CPU|AMD Socket F/G34/C32',
    'Dissipatori CPU|Accessori & Moduli Aggancio',
    'Dissipatori CPU|Intel Socket 115X',
    'Dissipatori CPU|Intel Socket 1366',
    'Dissipatori CPU|Intel Socket 2011',
    'Dissipatori CPU|Intel Socket 478',
    'Dissipatori CPU|Intel Socket 775',
    'Dissipatori CPU|Pasta Termoconduttiva',
    'Felpa Cappuccio|Consolero',
    'Felpa Cappuccio|Counter Strike',
    'Felpa Cappuccio|Fuck The Sun',
    'Felpa Cappuccio|GIGA',
    'Felpa Cappuccio|Gamers Girlfriend',
    'Felpa Cappuccio|Gaming Is Not A Crime',
    'Felpa Cappuccio|Gaming Nation',
    'Felpa Cappuccio|Godlike',
    'Felpa Cappuccio|Headshot',
    'Felpa Cappuccio|Studio 47',
    'Felpa Cappuccio|Terrorist',
    'Felpa Cappuccio|WOW',
    'Felpa Cappuccio|You bleed better...',
    'Felpe|Counter Strike',
    'Felpe|For The Horde',
    'Felpe|Padman',
    'Gadget / Toys|Energy Pack',
    'Gadget / Toys|Fun2Get',
    'Gadget / Toys|Gadget USB',
    'Gadget / Toys|Wooden Toys',
    'GamersWear|Accessori',
    'GamersWear|Cappelli',
    'Gaming|Accessori',
    'Gaming|Cuffie/Headset/Auricolari',
    'Gaming|Joystick & Gamepad',
    'Gaming|Killer NIC',
    'Gaming|Living',
    'Gaming|Mouse Feet',
    'Gaming|Mousebungees / Tendifilo',
    'Gaming|Nintendo DS / DSi',
    'Gaming|Nintendo Wii',
    'Gaming|Playstation',
    'Gaming|Sistemi Audio & Subwoofer',
    'Gaming|Tastiere',
    'Gaming|Volanti e Pedaliere',
    'Gaming|XBox 360',
    'Gaming|Zaini e Borse',
    'Griglie|Griglie Standard',
    'Griglie|Griglie UV Active',
    'IP Camera|Accessori / PoE',
    'IP Camera|IP Camera',
    'Illuminazione|FlexLights',
    'Illuminazione|LED',
    'Illuminazione|Neon Catodo Freddo / CCFL',
    'Illuminazione|RingPuks',
    'Illuminazione|Speciale',
    'LanCool|Accessori Lancool',
    'LanCool|Serie K58',
    'LanCool|Serie K62',
    'Lian Li|Accessori',
    'Lian Li|Lian Li - Armorsuit',
    'Lian Li|Lian Li - Big-Tower',
    'Lian Li|Lian Li - HDD Case',
    'Lian Li|Lian Li - Midi-Tower',
    'Lian Li|Lian Li - PC 60 Serie',
    'Lian Li|Lian Li - PC 7 Serie',
    'Lian Li|Lian Li - PC A7X Serie',
    'Lian Li|Lian Li - PC B25 Serie',
    'Lian Li|Lian Li - PC Q06 Serie',
    'Lian Li|Lian Li - PC TX Bench Serie',
    'Lian Li|Lian Li - PC Value Serie',
    'Lian Li|Lian Li - PC-Z Serie',
    'Lian Li|Lian Li - Super Case X Serie',
    'Lian Li|Parti di Ricambio',
    'Media PC - HTPC|Accessori',
    'Media PC - HTPC|Media Center HTPC',
    'Media PC - HTPC|Media Player',
    'Media PC - HTPC|PCoIP',
    'Media PC - HTPC|Tablet',
    'Media PC - HTPC|Telecomandi & Display',
    'Memorie|DDR2',
    'Memorie|DDR3 10666 - 1333Mhz',
    'Memorie|DDR3 12800 - 1600Mhz',
    'Memorie|DDR3 15000 - 1866Mhz',
    'Memorie|DDR3 16000 - 2000Mhz',
    'Memorie|DDR3 17000 - 2133Mhz',
    'Memorie|Secure Digital',
    'Memorie|SoDimm',
    'Memorie|USB Flash Drive',
    'Modding Case|Adesivi',
    'Modding Case|Bottoni & Pulsanti',
    'Modding Case|Display',
    'Modding Case|Fonoassorbenti',
    'Modding Case|Guaina Termorestringente',
    'Modding Case|Maniglie per Case',
    'Modding Case|Paratie Laterali',
    'Modding Case|Sleeve / Calze per Cavi',
    'Modding Cavi|Cavi & Adattatori',
    'Modding Cavi|Cavi con Sleeve',
    'Modding Cavi|Connettori',
    'Modding Cavi|Fascette',
    'Modding Cavi|Spirali Avvolgicavo',
    'Modding Cavi|Utensili',
    'Modding Ventole|Griglie',
    'Modding Ventole|Ventole Luminose',
    'Modding Ventole|Viti Ventole',
    'Modding|Colori & Vernici',
    'Modding|Windows Kits / Pannelli',
    'Monitor / TV LCD|Accessori Monitor',
    'Monitor / TV LCD|Monitor LCD / TFT / LED',
    'MousePad|Aerocool',
    'MousePad|CM Storm',
    'MousePad|Corepad',
    'MousePad|EVGA',
    'MousePad|Evo-G',
    'MousePad|Mionix',
    'MousePad|Ozone',
    'MousePad|QPad',
    'MousePad|Razer',
    'MousePad|Roccat',
    'MousePad|Saitek',
    'MousePad|Sharkoon',
    'MousePad|Speed-Link',
    'MousePad|SteelSeries',
    'MousePad|TTeSports',
    'MousePad|XFX',
    'MousePad|Zowie',
    'MousePad|Zykon',
    'Mouse|CM Storm',
    'Mouse|Corsair',
    'Mouse|Cyber Snipa',
    'Mouse|Logitech',
    'Mouse|Mionix',
    'Mouse|NZXT',
    'Mouse|Nexus',
    'Mouse|Ozone',
    'Mouse|QPAD',
    'Mouse|Razer',
    'Mouse|Revoltec',
    'Mouse|Roccat',
    'Mouse|Saitek',
    'Mouse|Sharkoon',
    'Mouse|Speed-Link',
    'Mouse|SteelSeries',
    'Mouse|TTeSports',
    'Mouse|Zalman',
    'Mouse|Zowie',
    'Notebook|Accessori Notebook',
    'Notebook|Borse per Notebook',
    'Notebook|Dissipatori Notebook',
    'Notebook|Notebook Skin',
    'Notebook|Sicurezza Notebook',
    'Polo - Donna|Counter Strike',
    'Polo - Uomo|Clanbase',
    'Polo - Uomo|Counter Strike',
    'Polo - Uomo|Joystick',
    'Polo - Uomo|M4',
    'Pompe|Adattatori Pompa',
    'Pompe|Pompe Aquacomputer',
    'Pompe|Pompe EK Water Blocks',
    'Pompe|Pompe Eheim',
    'Pompe|Pompe Hydor',
    'Pompe|Pompe Innovatek',
    'Pompe|Pompe Laing',
    'Pompe|Pompe MagiCool',
    'Pompe|Pompe Watercool',
    'Pompe|Silenziatori per Pompe',
    'Processori / CPU|Socket 1155 (Intel)',
    'Processori / CPU|Socket 1156 (Intel)',
    'Processori / CPU|Socket 2011 (Intel)',
    'Processori / CPU|Socket AM2/AM3/AM3+ (AMD)',
    'Radiatori|Griglie Installazione',
    'Radiatori|Kit Montaggio',
    'Radiatori|Radiatori Aqua Computer',
    'Radiatori|Radiatori BlackIce',
    'Radiatori|Radiatori EK Water Blocks',
    'Radiatori|Radiatori MagiCool',
    'Radiatori|Radiatori Watercool',
    'Radiatori|Radiatori innovatek',
    'SSD / HDD / BOX|Adattatori HD',
    'SSD / HDD / BOX|Adattatori SSD',
    'SSD / HDD / BOX|Antivibrazioni HD',
    'SSD / HDD / BOX|Backplane',
    'SSD / HDD / BOX|Borse / Suitcase',
    'SSD / HDD / BOX|Carrier / Slitte',
    'SSD / HDD / BOX|Cassetti HD',
    'SSD / HDD / BOX|Dissipatori HD',
    'SSD / HDD / BOX|Docking Station',
    '"SSD / HDD / BOX|HD da 1.8""',
    '"SSD / HDD / BOX|HD da 2.5""',
    '"SSD / HDD / BOX|HD da 3.5""',
    'SSD / HDD / BOX|NAS',
    'SSD / HDD / BOX|SOHO/RAID System',
    'SSD / HDD / BOX|SSD HSDL',
    'SSD / HDD / BOX|SSD PCIe',
    'SSD / HDD / BOX|SSD SAS',
    'SSD / HDD / BOX|SSD SATA II',
    'SSD / HDD / BOX|SSD SATA III',
    'SSD / HDD / BOX|SSD mSATA',
    'Schede Madri|AMD APU',
    'Schede Madri|AMD Socket AM2 / AM3',
    'Schede Madri|Intel ION',
    'Schede Madri|Intel Socket 1155',
    'Schede Madri|Intel Socket 1366',
    'Schede Madri|Intel Socket 2011',
    'Schede Video|AMD Graphics Card',
    'Schede Video|Dissipatori VGA',
    'Schede Video|NVIDIA Graphics Card',
    'Schede Video|USB Video Card',
    'Silverstone|Accessori',
    'Silverstone|Silverstone - Fortress Series',
    'Silverstone|Silverstone - Grandia Series',
    'Silverstone|Silverstone - HTPC',
    'Silverstone|Silverstone - Midi-Tower',
    'Silverstone|Silverstone - Precision Series',
    'Silverstone|Silverstone - Raven Series',
    'Silverstone|Silverstone - TemJin Series',
    'T-Shirt Manica Lunga|Admin',
    'T-Shirt Manica Lunga|Consolero',
    'T-Shirt Manica Lunga|Counter Strike',
    'T-Shirt Manica Lunga|Gaming Nation',
    'T-Shirt Manica Lunga|Godlike',
    'T-Shirt Manica Lunga|Headshot',
    'T-Shirt Manica Lunga|School Girls',
    'T-Shirt Manica Lunga|Studio 47',
    'T-Shirt|AFK',
    'T-Shirt|Admin',
    'T-Shirt|Camper',
    'T-Shirt|Consolero',
    'T-Shirt|Counter Strike',
    'T-Shirt|French School Girls',
    'T-Shirt|Fuck The Sun',
    'T-Shirt|Gamepad Dribbler',
    'T-Shirt|Gaming Is Not A Crime',
    'T-Shirt|Gaming Nation',
    'T-Shirt|Godlike',
    'T-Shirt|Headshot',
    'T-Shirt|LoL',
    'T-Shirt|NaturalBornSkiller',
    'T-Shirt|Padman',
    'T-Shirt|Player',
    'T-Shirt|Shootingstar',
    'T-Shirt|Studio 47',
    'T-Shirt|Terrorist',
    'T-Shirt|WASD',
    'T-Shirt|WoW',
    'T-Shirt|You bleed better...',
    'T-Shirt|eJunky',
    'Taniche|Accessori',
    'Taniche|Kit Luce',
    'Taniche|Taniche Aqua Computer',
    'Taniche|Taniche Bitspower',
    'Taniche|Taniche DangerDen',
    'Taniche|Taniche EK Water Blocks',
    'Taniche|Taniche FrozenQ',
    'Top|Counter Strike',
    'Top|French School Girls',
    'Top|Gamers Girlfriend',
    'Tubi|Molle Antipiega',
    'Tubi|Tubo 10/8 mm',
    'Tubi|Tubo 11/8 mm',
    'Tubi|Tubo 13/10 mm',
    'Tubi|Tubo 14/10 mm',
    'Tubi|Tubo 14/11 mm',
    'Tubi|Tubo 16/11 mm',
    'Tubi|Tubo 16/13 mm',
    'Tubi|Tubo 19/13 mm',
    'Tubi|Tubo 6/4 mm',
    'Tubi|Tubo 8/6 mm',
    'Utensileria & Montaggio|Accessori Antistatici',
    'Utensileria & Montaggio|Ricambi & Accessori',
    'Utensileria & Montaggio|Utensili',
    'Utensili|Accessori',
    'Utensili|Cacciavite / Chiavi',
    'Utensili|Contenitori',
    'Utensili|Cutter / Tronchesi',
    'Utensili|Kit Attrezzi',
    'Utensili|Pinze',
    'Utensili|Pulizia',
    'Utensili|Punte / Maschio per filettatura',
    'Utensili|Sicurezza',
    'Utensili|Tester',
    'VGA / RAM / CHIP|Dissipatori CHIP',
    'VGA / RAM / CHIP|Dissipatori RAM',
    'VGA / RAM / CHIP|Dissipatori VGA',
    'VGA Cooler|Aqua Computer',
    'VGA Cooler|DangerDen',
    'VGA Cooler|EK Waterblock',
    'VGA Cooler|Watercool',
    'VGA Cooler|innovatek',
    'Ventole|Adattatori / Cavi',
    'Ventole|AntiVibrazioni',
    'Ventole|Convogliatori',
    'Ventole|Fan  di Sistema',
    'Ventole|Fan 100 mm',
    'Ventole|Fan 120 mm',
    'Ventole|Fan 140 mm',
    'Ventole|Fan 40 mm',
    'Ventole|Fan 50 mm',
    'Ventole|Fan 60 mm',
    'Ventole|Fan 80 mm',
    'Ventole|Fan 92 mm',
    'Ventole|Fan superiori 140 mm',
    'Ventole|Filtri Antipolvere',
    'Ventole|Regolatori Ventole',
    'WaterCooling|Accessori',
    'WaterCooling|Additivi',
    'WaterCooling|Case con Kit Liquido',
    'WaterCooling|Controller',
    'WaterCooling|HD Cooler',
    'WaterCooling|Kit Liquido Esterni',
    'WaterCooling|Kit Liquido Interni',
    'WaterCooling|Mosfet Cooler',
    'WaterCooling|RAM Cooler',
    'Xigmatek|Asgard Series',
    'Xigmatek|Elysium Series',
    'Xigmatek|Midgard Series',
    'Xigmatek|Utgard Series',
    'iPhone/iPad/iPod|Apple iPad/iPad2',
    'iPhone/iPad/iPod|Apple iPhone',
    'iPhone/iPad/iPod|Apple iPod',
    'Alimentatori|XFX',
    'BitFenix|BitFenix - Raider',
    'Case|Case Rack',
    'Case|Soundgraph',
    'Cavi Audio/Video|cavi / adattatori DisplayPort',
    'Gaming Rig|Gaming Rig',
    'Gaming|Gamer Cube',
    'Gaming|Playstation 3',
    'Gaming|Pro Flight',
    'iPhone/iPad/iPod|Apple iPhone',
    'Lian Li|Lian Li - PC-6 Serie',
    'Lian Li|Lian Li - PC-A Serie',
    'Lian Li|Lian Li - PC-B Serie',
    'Lian Li|Lian Li - PC-Q Serie',
    'Lian Li|Lian Li - PC-T Serie',
    'Lian Li|Lian Li - PC-TU Serie',
    'Lian Li|Lian Li - PC-V Serie',
    'Lian Li|Lian Li - PC-X Serie',
    'Luci / Light LED|Cromoterapia',
    'Luci / Light LED|Faretti LED GU10',
    'Luci / Light LED|Faretti LED MR11',
    'Luci / Light LED|Faretti LED MR16',
    'Luci / Light LED|Lampadine LED E27',
    'Luci / Light LED|LED Ball',
    'Luci / Light LED|Striscia LED',
    'Luci / Light LED|Trasformatori/Controller',
    'Memorie|DDR1',
    'Memorie|PC3-10666 - 1333Mhz',
    'Memorie|PC3-12800 - 1600Mhz',
    'Memorie|PC3-15000 - 1866Mhz',
    'Memorie|PC3-16000 - 2000Mhz',
    'Memorie|PC3-17000 - 2133Mhz',
    'Memorie|PC3-19200 - 2400Mhz',
    'Memorie|SD / micro SD',
    'Mouse|Eclipse',
    'Mouse|Mad Catz',
    'Mouse|Speedlink',
    'MousePad|Mad Catz',
    'MousePad|Speedlink',
    'Networking|Accessori / PoE',
    'Networking|IP Camera',
    'Networking|Router',
    'Networking|VoIP',
    'Processori / CPU|Socket 1366 (Intel)',
    'Radiatori|Radiatori XSPC',
    'Schede Madri|Intel Socket 1366',
    'SSD / HDD / BOX|Controller',
    'SSD / HDD / BOX|HD da 1.8"',
    'SSD / HDD / BOX|HD da 2.5"',
    'SSD / HDD / BOX|HD da 3.5"',
    'SSD / HDD / BOX|HD USB 3.0',
    'VGA Cooler|Aqua Computer - Waterblock VGA',
    'VGA Cooler|EK Water Block - Waterblock VGA',
    'VGA Cooler|Innovatek - Waterblock VGA',
    'VGA Cooler|Watercool - Waterblock VGA',
    'VGA Cooler|XSPC - Waterblock VGA',
    'XBox 360|Cavi / Adattatori / Accessori',
    'Streacom|Serie ST-FC10',
    'PlayStation 3|Racing Wheel / Volanti',
    'LEGO |LEGO Star Wars',
    'LEGO |LEGO Architecture',
    'MousePad|Akasa',
    'Modding Case|Ricambi Lian Li',
    'Accessori|Tavolette Grafiche',
    'Xigmatek|Alfar Series',
    'Gaming|Ps Vita',
    'Notebook / Tablet|Dissipatori Notebook',
    'Notebook / Tablet|Alimentatori',
    'Case|anidees',
    'LEGO |LEGO Games',
    'Case|Nox',
    'Gaming|Nintendo DS / DSi / DS 3D XL',
    'Nintendo Wii|Accessori',
    'Notebook / Tablet|Sicurezza',
    'MousePad|Corsair',
    'Lian Li|Lian Li - PC-D Serie',
    'LEGO |LEGO City',
    'SSD / HDD / BOX|Adattatori SSD / HD',
    'Gadget / Toys|Arctic RC Toys',
    'LEGO |LEGO DC Universe Super Heroes',
    'LEGO |LEGO Technic',
    'Notebook / Tablet|Borse / Custodie',
    'Processori / CPU|Socket FM1 (AMD)',
    'Taniche|Taniche XSPC',
    'Cavi / Adattatori|Cavi / Adattatori Rete',
    'Pompe|Pompe XSPC',
    'SSD / HDD / BOX|HD da 3.5 pollici',
    'Schede Madri|AMD FM2',
    'Networking|Wireless Network',
    'PlayStation 3|Light Gun',
    'PlayStation 3|Cavi / Adattatori / Accessori',
    'BitFenix|BitFenix - Ghost',
    'PlayStation 3|GamePad',
    'Notebook / Tablet|Accessori',
    'Gadget / Toys|Opere di Luce',
    'LEGO |LEGO Bricks & More',
    'HTPC - Streacom|Serie ST-FC9',
    'Processori / CPU|Socket FM2 (AMD)',
    'Lian Li|Lian Li - PC-7 Serie',
    'Radiatori|Staffe ed Adattatori',
    'Accessori|Adattatori USB/FireWire/Bluetoot',
    'Ventole|Convogliatori / Adattatori',
    'XBox 360|GamePad',
    'Lian Li|Lian Li - PC-C Serie',
    'SSD / HDD / BOX|HD da 2.5 pollici',
    'Nintendo Wii|GamePad & Controller',
    'Radiatori|Convogliatori',
    'LEGO |LEGO Creator',
    'LEGO |LEGO Lord Of The Rings',
    'Abbigliamento Gamer|Cappelli',
    'LEGO |LEGO Castle',
    'LEGO |LEGO Legends of Chima',
    'Networking|Powerline',
    'Nintendo Wii|Adattatori & Cavi',
    'Abbigliamento Gamer|Accessori',
    'LEGO |LEGO Ninjago',
    'T-Shirt|Corsair',
    'MousePad|Zalman',
    'Xbox 360|GamePad',
    'Notebook|Borse / Custodie',
    'Tablet / iDevice|Apple iPod',
    'Tablet / iDevice|Apple iPad/iPad2',
    'Box Esterni HD|Box Wireless',
    'Tubi|Tubo 16/10 mm',
    'Gaming|PSP',
    'Silverstone|Silverstone - Sugo Series',
    'Alimentatori|be quiet!',
    ' . Ventole|Adattatori / Cavi',
    'Tablet / iDevice|Asus Tablet',
    'Case|XSPC',
    'LEGO |LEGO Teenage Mutant Ninja Turtle',
    'Alimentatori|EVGA',
    'Memorie|PC3-22400 - 2800Mhz',
    'Tablet / iDevice|Apple iPhone',
    'Gaming|Occhiali / Gaming Eyewear',
    'Xbox 360|Cavi / Adattatori / Accessori',
    'Mouse|Asus',
    'MousePad|Krom',
    'Case|Phanteks',
    'Notebook|Sicurezza',
    'BitFenix|BitFenix - Comrade',
    'Networking|Switch & Hub',
    'Gaming|Registratori Live HD',
    'Mouse|Laura Sapiens',
    'Xigmatek|Aquila Series',
    'Case|Armadi e Accessori',
    'Schede Madri|Intel Socket 1150',
    'LEGO |LEGO Mindstorms',
    'LEGO |LEGO Friends',
    'T-Shirt|EK-Tshirt',
    'Processori / CPU|Socket 1150 (Intel)',
    'BitFenix|BitFenix - Ronin',
    'Memorie|PC3-23460 - 2933Mhz',
    'Case|MicroCool',
    'LEGO |LEGO Disney Princess',
    'Networking|Schede di Rete PCIe',
    'LEGO |LEGO Galaxy Squad',
    'Accessori|Adattatori da viaggio',
    'Pompe|Pompe aqua computer',
    'Notebook|Notebook',
    'Mouse|Aerocool',
    'Notebook|Alimentatori',
    'LEGO |LEGO Marvel Super Heroes',
    'LEGO |LEGO Hero Factory',
    'Radiatori|Radiatori Feser',
    'Luci / Light LED|Faretti LED G35',
    'LEGO |LEGO The Hobbit',
    'Case|EVGA',
)

EXCLUDED_CATEGORIES = (
    'B-Stock|B-Stock',
    '|',
    '. Lian Li|Lian Li - PC-6 Serie',
)

EXCLUDED_MANUFACTURERS = (
    "Drako's Kits",
    "Drako's Bundle",
    "Drako's Mods",
    'Mad Catz',
    'Razer',
)
